use crate::data::generation::record_generator::RecordGenerator;
use crate::data::record::Record;
use crate::data::record_io_error::RecordIOError;

/// Writes records to a given file, generated by the given RecordGenerator
pub trait RecordWriter<T: Record> {
    fn write(&self, path: &str, generator: &mut dyn RecordGenerator<T>, limit: usize) -> Result<(), RecordIOError>;
}